Price cap adapters
bgd-labs/cl-synchronicity-price-adapter pull request #33
Opened 2024-01-08 09:30 UTC by rustboyar

2024-01-08 10:15 UTC, kyzia551 requested changes

2024-01-08 10:15 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +  uint8 public immutable DECIMALS;
does it makes sense to have it public if we also has `decimals()`?

2024-01-08 10:15 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +   * @notice Price feed for (cbETH / Base) pair
is it for cbETH always, and where is the info about USD?

2024-01-08 10:15 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +  uint256 public immutable SNAPSHOT_RATIO;
don't we want to have a way to correct snapshot ratio and timestamp overtime?
cc: @eboadom

2024-01-08 10:15 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +        (SNAPSHOT_RATIO * _maxYearlyRatioGrowth * (block.timestamp - SNAPSHOT_TIMESTAMP)) /
do we expect that it can grow in absolute ratio, or relative?

For example, if 
```
SNAPSHOT_RATIO = 2 
_maxYearlyRatioGrowth = 6%
block.timestamp - SNAPSHOT_TIMESTAMP =  SECONDS_PER_YEAR
```
Then maxRatio can be:
Relative: 2 + 2 * 6%
Absolute: 2 + 6%

Imo should be the Absolute option

cc: @eboadom

2024-01-08 10:15 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +    int256 price = (basePrice * ratio) / int256(10 ** RATIO_DECIMALS);
Shouldn't we divide by 10000 somewhere because we multiplied by that in the `maxRatio` calculation?

2024-01-08 10:15 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +  function getBaseLatestAnswer() internal view returns (int256) {
Why do we have this method? It used only once, and we can't overload it because it's not virtual

2024-01-08 10:15 UTC, kyzia551 commented on tests/PriceCapAdapters/WstETHPriceCapAdapterTest.t.sol
> +  function testLatestAnswer() public {
could be good to add a bit of fuzzing to the tests

2024-01-08 10:49 UTC, rustboyar commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +    int256 price = (basePrice * ratio) / int256(10 ** RATIO_DECIMALS);
we didn't multiplied

2024-01-08 10:51 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +    int256 price = (basePrice * ratio) / int256(10 ** RATIO_DECIMALS);
Ah, yes, sorry, we divided before, by what we compensate?

2024-01-08 10:52 UTC, rustboyar commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +    int256 price = (basePrice * ratio) / int256(10 ** RATIO_DECIMALS);
its percentage, 5_00 / 100_00

2024-01-08 10:55 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +    int256 price = (basePrice * ratio) / int256(10 ** RATIO_DECIMALS);
Ah, ok, but then could be better to use existing PercentageMath lib, to make it more readable

2024-01-08 10:59 UTC, rustboyar commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +        (SNAPSHOT_RATIO * _maxYearlyRatioGrowth * (block.timestamp - SNAPSHOT_TIMESTAMP)) /
didn't understand

2024-01-08 15:14 UTC, rustboyar commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +  uint8 public immutable DECIMALS;
i think its for some backward compatibility with aave v2

2024-01-09 10:33 UTC, kyzia551 requested changes

2024-01-09 10:33 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +  uint16 private _maxYearlyRatioGrowthPercent;
why do we need it? Just to have it more explanatory for the end user?

We can modify `getMaxYearlyGrowthRatePercent` to return `_ratioGrowthPerSecond * SECONDS_PER_YEAR`

2024-01-09 10:33 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +  uint256 private _ratioGrowthPerSecond;
I would name it `_maxRatioGrowthPerSecond`

2024-01-09 10:33 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +    return int256(price);
```suggestion
    return price;
```

2024-01-09 10:33 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/MaticPriceCapAdapter copy.sol
> +// SPDX-License-Identifier: MIT
why is this file named as `..._copy.sol`?

2024-01-09 10:33 UTC, kyzia551 commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +      _snapshotRatio + _ratioGrowthPerSecond * (block.timestamp - _snapshotTimestamp)
@eboadom please verify

2024-01-09 14:00 UTC, eboadom commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +  uint16 private _maxYearlyRatioGrowthPercent;
Agree, this should be an abstraction over `_ratioGrowthPerSecond` on the getter

2024-01-09 14:00 UTC, eboadom commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +  uint256 private _ratioGrowthPerSecond;
Agree

2024-01-09 22:12 UTC, eboadom commented
On the header of the contract (`PriceCapAdapterBase`) we should add extensive documentation like:
- Better description of what is the main goal: capping an asset which should have a limited correlation to an underlying
- Which is the general idea of `latestAnswer()`, with a numeric example using one of the assets.
- How is suppose to be managed: updating with `setCapParameters()` periodically. And by who: pool_admin and risk_admin of Aave to start with.
- That we assume simple interest and not compounded, as it is precise enough approximation, and saves important cost of calculations.
- How is the format of `_maxRatioGrowthPerSecond`, with a numeric example

2024-01-09 22:13 UTC, eboadom commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +  uint256 internal constant SECONDS_PER_YEAR = 365 days;
Constants up, variables after

2024-01-09 22:13 UTC, eboadom commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +  function setCapParameters(
Events are missing

2024-01-09 22:14 UTC, eboadom commented on src/contracts/PriceCapAdapters/PriceCapAdapterBase.sol
> +    _snapshotRatio = snapshotRatio;
Given you do this assignment on the setter too, I would probably do an internal function, calling it from here, and from an external setter doing the access control validation

2024-01-10 09:03 UTC, kyzia551 requested changes

2024-01-16 11:49 UTC, closed without merging